### ISSUE TITLE
Bitfocus Companion - Connection stuck at waiting to start

### ISSUE THREAD

**Issue by mrhhats** [bitfocus/companion-module-samsung-smarttv#1]
Hi there! trying to get this to work. Bitfocus Companion 3.0.0 RC1

Added connection and it just spins on 'waiting for connection to start' - am i missing something?

<img width="1527" alt="image" src="https://github.com/bitfocus/companion-module-samsung-smarttv/assets/111146190/b7e968b0-3457-497c-b334-1666135606df">

**Comment by peternewman** [comment]
It currently says disabled.

I think from my experience the module normally isn't launching for some reason.

Is this happening with a full download or are you trying to add the module via the dev modules folder?

**Comment by matt-flaig** [comment]
@mrhhats,

If you click the Terminal/Debug icon (to the left of the trash can), a new webpage will open which will show why it's erroring.

Most likely, if you've placed the files in the Developer Modules folder you need to run `npm install` inside the "companion-module-samsung-smarttv" folder to download the node modules required to run this Companion module. (It will not run without them installed).

Feel free to report any errors occurring in the module and I'll try to reproduce on my end!

**Comment by peternewman** [comment]
> Edit: I'll try to upload some builds of the module soon so it's not so complicated!

If you just get it added to the dev builds, I think that all happens automagically so it's just available.

Alternatively the trick would be to add a GitHub action which builds each branch and any releases and uploads the artefacts, then it will happen automagically!

**Comment by mrhhats** [comment]
ok that npm install did it for me! thanks!
