### ISSUE TITLE
Add this module to the beta builds

### ISSUE THREAD

**Issue by peternewman** [bitfocus/companion-module-samsung-smarttv#7]
While I've not actually tested all of this module, I did some pretty trivial changes to switch to samsung-remote (from https://github.com/natalan/samsung-remote ) and it works fine, so I think the vast majority of the module is fine, and any errors would be likely to be in the npm package if they existed. Anyway PR for that coming soon...

There's some notes here for how to get it added to the beta builds:
https://github.com/bitfocus/companion-module-base/wiki/Module-development-101#sharing-your-code

**Comment by dnmeid** [comment]
@matt-flaig you are the maintainer of this module.
There seems to be interest in use of this module. It seems to me to be quite ready and just needs few finishing touches.
Please tell us on the slack channel CFG7HAN5N if it is finished and can be included in the betas.

**Comment by echalupka** [comment]
@matt-flaig @peternewman any updates on this? Would love to get access to this module.

**Comment by matt-flaig** [comment]
@echalupka

Unfortunately, this module is still in some development/beta state as I've encountered issues with certain Samsung TVs when using this module. I believe you can side-load this module in Companion if you're running version 3 or later (and have access to command line to use `npm` to install the dependancies).

Hopefully I have time to pick this up in the future, but my access to Samsung TVs (to test with) is somewhat limited. 📺

**Comment by peternewman** [comment]
@matt-flaig I don't know what the official line is from Companion people, but I'd say if it works for control of some Samsung TVs (which it looks like it does from your readme), then you should get it added to the beta builds at least (and from there the main releases). Otherwise the module risks never getting released (e.g. it won't support the pre-2016 models of Samsung without a rework/using two npm libraries).

I'd think if you're just clear about what's been tested and asking people to raise issues if they have problems, then you've done more than enough. Plus the easier you make it for others to run it (via the beta builds), the greater the chance you'll get more testers (e.g. the people who don't need to control a Samsung but happen to have one hanging around/used somewhere) and more info on what's going wrong if it doesn't work.

**Comment by josephdadams** [comment]
I'm going to tag a release, let's get this module out in the wild and see how it goes.
